# Generated by Django 4.0 on 2022-03-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table',
        ),
    ]
