# Generated by Django 4.0 on 2022-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Contrag',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Done',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='ToDo',
            field=models.IntegerField(null=True),
        ),
    ]
