# Generated by Django 3.2.9 on 2022-04-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20220329_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=100, null=True)),
                ('Mass', models.FloatField(null=True)),
                ('Contrag', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
