# Generated by Django 3.2.9 on 2022-04-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='weights',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
