# Generated by Django 3.2.9 on 2022-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_weights_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weights',
            name='Car_Num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
