# Generated by Django 3.2.9 on 2022-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_weights_pba'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Amount_Cars',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='Num_Cars',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
