# Generated by Django 3.2.9 on 2022-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_driver_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='airport_msg_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
